name: waseelatask
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.1
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  get_it: ^9.2.0
  pretty_dio_logger: ^1.4.0
  top_snackbar_flutter: ^3.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  intl: ^0.20.2

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/lang/
